### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheIntelloBox** [steve4744/TNTRun#20]
[12:37:01] [Server thread/WARN]: [TNTRun_reloaded] Task #1231349 for TNTRun_reloaded v6.7.1 generated an exception
java.lang.NullPointerException: null
	at tntrun.arena.handlers.GameHandler$4.run(GameHandler.java:356) ~[TNTRun_reloaded.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1402]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1402]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1402]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1402]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1402]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1402]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by steve4744** [comment]
Hi,
The error is from the code that creates the on-screen scoreboard.
Could you post the scoreboard section from your config.yml please.
Thanks.

**Comment by TheIntelloBox** [comment]
scoreboard:
  waiting:
  - '&fBienvenue au TNTRun'
  - '&a '
  - '&fArène: &6&l{ARENA}'
  - '&b '
  - '&fJoueurs: &a&l{PS}&7&l/&c&l{MPS}'
  - '&c '
  - '&fCommence dans: &6&l{COUNT}'
  playing:
  - '&fPartie de TNTRun'
  - '&fsur la Map: &6&l{ARENA}'
  - '&b '
  - '&fJoueurs: &a&l{PS}&7&l/&c&l{MPS}'
  - '&c '
  - '&fPerdants: &a&l{LOST}'
  - '&2 '
  - '&fFin dans: &c&l{LIMIT}'

**Comment by steve4744** [comment]
That looks ok - I can't seem to reproduce the error.
Does this happen on every arena or just one? 
Does it happen everytime a game starts or only certain circumstances?
Presumably you get the "waiting" scoreboard with the countdown before the game actually starts?
Thanks.

**Comment by steve4744** [comment]
I couldn't reproduce this, and there has been no update for 3 months.
