### ISSUE TITLE
Tntrun setup ERROR

### ISSUE THREAD

**Issue by SamLam140330** [steve4744/TNTRun#31]
When I try to setup my arena using /trsetup setarena tntrun1, I have got an error. Do you know why? Could you please help me to fix it?

.........
[04:16:48 INFO]: SamLam140330 issued server command: /clear
[04:26:24 INFO]: 你可以使用 §2/qb toggle §f來顯示/隱藏右方資訊
[04:26:24 INFO]: Updating leaderboards
[04:26:24 INFO]: Holograms Updated!
[04:26:36 INFO]: SamLam140330 issued server command: /clear
[04:26:38 INFO]: SamLam140330 issued server command: //wand
[04:27:42 INFO]: SamLam140330 issued server command: /trsetup setarena tntrun1
[04:27:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trsetup' in plugin TNTRun_reloaded v7.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3;
        at tntrun.selectionget.WEIntegration.getPlayerSelection(WEIntegration.java:54) ~[?:?]
        at tntrun.selectionget.WEIntegration.getLocations(WEIntegration.java:41) ~[?:?]
        at tntrun.selectionget.PlayerSelection.getPlayerSelection(PlayerSelection.java:47) ~[?:?]
        at tntrun.commands.setup.arena.SetArena.handleCommand(SetArena.java:46) ~[?:?]
        at tntrun.commands.setup.SetupCommandsHandler.onCommand(SetupCommandsHandler.java:133) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        ... 15 more
ver
[04:28:07 INFO]: This server is running CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[04:28:07 INFO]: Checking version, please wait...
[04:28:08 INFO]: You are 1 version(s) behind
[04:30:33 INFO]: SamLam140330 issued server command: /tr cmds
........
[04:46:14 ERROR]: Error occurred while disabling TNTRun_reloaded v7.6 (Is it up to date?)
java.lang.NullPointerException: null
        at tntrun.utils.Bars.removeAll(Bars.java:96) ~[?:?]
        at tntrun.TNTRun.saveArenas(TNTRun.java:151) ~[?:?]
        at tntrun.TNTRun.onDisable(TNTRun.java:129) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:371) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:370) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:621) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:766) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[04:46:14 INFO]: [ActionHealth] Disabling ActionHealth v3.2.8
[04:46:14 INFO]: [WorldGuard] Disabling WorldGuard v7.0.0-SNAPSHOT;0dc5781
.........

**Comment by steve4744** [comment]
Hi,

> Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/math/BlockVector3

This will be due to you having an old version of WorldEdit 7 prior to the new vector system update. I would suggest getting at least the Beta-05 release from https://dev.bukkit.org/projects/worldedit/files or the latest snapshot from EnginHub.org.

You will need to upgrade WorldGuard too as the version in the stacktrace above (WorldGuard v7.0.0-SNAPSHOT;0dc5781) is 5 months old and prior to the new vector system. You can get the latest Beta release here:
https://dev.bukkit.org/projects/worldguard/files

**Comment by SamLam140330** [comment]
Oh, after update the world guard and the world edit, it works perfectly, thank you so much for the help!

**Comment by steve4744** [comment]
No problem - thanks for letting me know.
